export const breadcrumbData = [
    { url: "/admin/index", title: "Trang chủ" },
    { url: "/admin/product", title: "Sản phẩm" },
    { url: "/admin/sizes", title: "Quản Lý Size" },
    { url: "/admin/categories", title: "Danh mục sản phẩm" },
    { url: "/admin/product-attributes", title: "Quản lý thuộc tính" },
    { url: "/admin/suppliers", title: "Nhà cung cấp" },
    { url: "/admin/stock-receipts", title: "Phiếu nhập kho" },
    { url: "/admin/brands", title: "Thương hiệu" },
    { url: "/admin/invoices", title: "Hóa đơn" },
    { url: "/admin/detailed-invoices", title: "Chi tiết hóa đơn" },
    { url: "/admin/account", title: "Người dùng" },
    { url: "/admin/accountStaff", title: "Nhân viên" },
    { url: "/admin/roles", title: "vai trò" },
    { url: "/admin/products-distinctives", title: "Thuộc tính sản phẩm" },
    { url: "/admin/statistics-documents", title: "Tài liệu thống kê" },
    { url: "/admin/charts", title: "Biểu đồ thống kê" },
    { url: "/admin/verification", title: "Thống kê Tài khoản" },
];
