export const breadcrumbDataUser = [
  { url: "/", title: "Trang chủ" },
  { url: "/products", title: "Sản phẩm" },
  { url: "/seefulldetails/id", title: "Chi tiết sản phẩm" },
  { url: "/cart", title: "Giỏ hàng" },
  { url: "/checkout", title: "Thanh toán" },
  { url: "/profile", title: "Tài khoản" },
  { url: "/orders", title: "Đơn hàng" },
  { url: "/category", title: "Danh mục" },
  { url: "/wishlist", title: "Yêu thích" },
  { url: "/about", title: "Giới thiệu" },
  { url: "/contact", title: "Liên hệ" },
  { url: "/news", title: "Tin tức" },
  { url: "/faqs", title: "FAQs" },
];
